### ISSUE TITLE
Force Remove

### ISSUE THREAD

**Issue by aminnairi** [vladshcherbin/rollup-plugin-delete#1]
There is currently no way to use the [force](https://github.com/sindresorhus/del#force) option from [del](https://github.com/sindresorhus/del). This is useful for remove parents files/folders for instance.

**Comment by vladshcherbin** [comment]
@aminnairi hey, I've added possibility to use del package options in 0.2.0 and released it.

Check [docs](https://github.com/vladshcherbin/rollup-plugin-delete#del-package-options) and try if it works for you 😉

**Comment by mssucksalot** [comment]
It is time to reopen this issue.

**Comment by mssucksalot** [comment]
@vladshcherbin I see you `doc` link follows "https://github.com/vladshcherbin/rollup-plugin-delete#del-package-options".

There is no information about `force` option there. So I assumed it is removed from config.

**Comment by vladshcherbin** [comment]
@mssucksalot oh, I see. The readme was updated since the time this issue was created and resolved, it's just a small sentence about passing rest options to internal `del` package at the end.

All `del` options should be working, `force` is one of them. Sorry for confusion 🙌
