### ISSUE TITLE
TypeScript Support

### ISSUE THREAD

**Issue by aminnairi** [vladshcherbin/rollup-plugin-delete#2]
**This issue is related to a feature request**. It would be nice to have a definition type (at least) for VSCode Intellisense to trigger without having to go to the GitHub page (when using it, people will still go here to follow the installation instructions and get more informations of course).

It would be even greater if the code was written in TypeScript (but that is not necessary as an `index.d.ts` is enough with `{ "types": "./index.d.ts" }` in `package.json` in order to trigger the Intellisense).

**The solution I would like to be implemented** should follow these guidelines:
- A `index.d.ts` at the root of this project with the necessary [declaration instruction](https://www.typescriptlang.org/docs/handbook/declaration-files/by-example.html) related to TypeScript.
- A `"types"` key in the `package.json` with the value of `"index.d.ts"` (or the path to that file if it is in a directory) for VSCode & TypeScript Intellisense to trigger automatically.

**Alternatives** would be to create a package and push the type definition file to `@types/rollup-plugin-delete`. I am not a big fan of that solution as it may require to maintain an entire new repository (I guess, never had the opportunity to try) and it seems a little overkill to have to use `npm install --save-dev rollup-plugin-delete @types/rollup-plugin-delete` since the type definition file should not be large.

**Another alternative** would be to (re?)write the project using TypeScript. Since TypeScript is just a superset of JavaScript, this should not be hard to implement and would probably only require the adding of types to function parameters and variables.

**Comment by vladshcherbin** [comment]
@aminnairi hey, thanks for the suggestion.

Personally, I'm not using TS and don't want to convert source code to TS. I would accept a PR with TS types to add TS support.

**Comment by vladshcherbin** [comment]
After the discussion and conclusion of https://github.com/vladshcherbin/rollup-plugin-delete/pull/3 here is a PR - https://github.com/DefinitelyTyped/DefinitelyTyped/pull/32598

**Comment by vladshcherbin** [comment]
Published - https://www.npmjs.com/package/@types/rollup-plugin-delete

Seems to be working:

![screen shot 2019-01-31 at 05 10 07](https://user-images.githubusercontent.com/6711845/52025791-bfddc080-2516-11e9-8f69-3916c16a3ee9.png)

@aminnairi try it in your project to confirm that it works too 😉

**Comment by vladshcherbin** [comment]
@aminnairi yeah, you can always write what error you have and we'll try to figure out how to reproduce and fix it.
