### ISSUE TITLE
Increased verbosity

### ISSUE THREAD

**Issue by aminnairi** [vladshcherbin/rollup-plugin-delete#5]
Hi there,

This feature request is about the `verbosity` parameter.

The current behavior is that deleted files and folders are counted.

I think this would be good to have another level of verbosity where the names of the files & folders are enumerated as well. Especially on small to medium projects where enumerating deleted files & folders is both reassuring & not too overwhelming in the terminal.

What do you think?

**Comment by vladshcherbin** [comment]
@aminnairi Hey, not sure I understand correctly, how it should look. Can you provide an example, how it's now and how it should look like?

**Comment by aminnairi** [comment]
For instance, I have the `build` folder where I put all my transpiled files from the `sources` folder. Inside the build folder, I have several files that have been built (for now just one, but the project is growing...). When I configure Rollup with your plugin, I'm generally using the folder name for a bulk delete.

```javascript
import { rollup } from 'rollup';
import del from 'rollup-plugin-delete';

export default {
  plugins: [ del({ targets: [ resolve('build'), verbose: true ] }) ]
};
```

This way, I'm able to do clean (re)build of my project. And with the `verbose` option, I'm able to see that the `build` folder has indeed been deleted during the process.

```console
Deleted files and folders: 1
/path/to/my/project/build
```

What could be nice is to have the output say something like:

```console
Deleted files: 1
/path/to/my/project/build/index.js
Deleted folders: 1
/path/to/my/project/build
```

With an option like so:

```typescript
import del = require('del');
import { Plugin } from 'rollup';

export interface Options extends del.Options {
    /**
     * Patterns of files and folders to be deleted.
     * @default []
     */
    readonly targets: ReadonlyArray<string> | string;

    /**
     * Outputs removed files and folders to console.
     * @default false
     */
    readonly verbose?: boolean | 'all'; // this 'all' parameter could be the one triggering the increased output verbosity (or anything else...)
}

export default function(options?: Options): Plugin;
```

And used in the Rollup configuration file:

```javascript
import { rollup } from 'rollup';
import del from 'rollup-plugin-delete';

export default {
  plugins: [ del({ targets: [ resolve('build'), verbose: 'all' ] }) ]
};
```

Again, this is a feature request. Maybe this is not something you intend to do anytime soon. Or maybe this is a lower level that you just can't have your hands on (but looking at the TypeScript definition file, it seems you can have some leverage on it). I just though this would be good to have another layer of verbosity just for the reassurance part of knowing that the plugin indeed removed the build files effectively (as the synchronization with IDE, like VSCode is pretty slow when deleting things too quickly).

**Comment by vladshcherbin** [comment]
@aminnairi try to check this with:

```js
export default {
  plugins: [ del({ targets: [ resolve('build/**'), verbose: true ] }) ]
};
```

Maybe it can already do this :)

**Comment by aminnairi** [comment]
Thanks. That works great with the glob option! Maybe this could be documented like a hint in the `verbose` for newcomers like me?

**Comment by vladshcherbin** [comment]
@aminnairi I've added a note in readme as you suggested. Thanks 😉
